# Site settings
title: "Kim Torberntssons Blog"
email: kimtorberntsson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is my (Kim Torberntsson's) personal homepage, which contains
    my blog, a page with a few photos and my resume. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kimtorberntsson.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
